#Unit One: introduction to deep learning with PyTorch

In [ ]:
import torch

# Tensors

In [ ]:
array=[[1,2,3],[4,5,6]]
tensor=torch.tensor(array) #load from list

In [ ]:
import numpy as np
np_array=np.array(array)
np_tensor=torch.from_numpy(np_array)#load from array

In [ ]:
#tensor shape
array=[[1,2,3],[4,5,6]]
tensor=torch.tensor(array)
print(tensor.shape)
#tensor data type
print(tensor.dtype)
#tensor device
print(tensor.device)

torch.Size([2, 3])
torch.int64
cpu


In [ ]:
#Tensor operation. Most MumPy array operations can be performed by PyTorch tensors.
a=torch.tensor([[1,1],
                [2,2]])
b=torch.tensor([[2,2],
                [3,3]])
print(a+b) # compatible shapes
c=torch.tensor([[2,3,4],
                [3,3,5]])
#print(a+c) #incompatible shapes
print(a*b) # element-wise multiplication


tensor([[3, 3],
        [5, 5]])
tensor([[2, 2],
        [6, 6]])


#Creating First Neural Network

In [ ]:
import torch.nn as nn
# create input tenspr with three features
input_tensor=torch.tensor(
    [[0.3471,0.4547,-0.2356]]
)
#define first linear layer
linear_layer=nn.Linear(in_features=3,out_features=2)
#pass the input through thelinear layer to get output of first layer
output=linear_layer(input_tensor)
print(output)

tensor([[ 0.1320, -0.2182]], grad_fn=<AddmmBackward0>)


In [ ]:
#GETTING TO KNOW LINEAR LAYER OPERATION
# each linear layer has a weight and bias
print(linear_layer.weight)
print(linear_layer.bias)

Parameter containing:
tensor([[-0.4249, -0.3922,  0.3395],
        [ 0.0618, -0.1022,  0.1398]], requires_grad=True)
Parameter containing:
tensor([ 0.5378, -0.1603], requires_grad=True)


In [ ]:
#STACKING LAYERS WITH nn.Sequencial()

#Create netowrk with three linear layers
model=nn.Sequential(
    nn.Linear(10,18),
    nn.Linear(18,20),
    nn.Linear(20,5)
)
input=torch.randn(1,10)
output=model(input)

print(output)

tensor([[ 0.1911,  0.0246, -0.1744,  0.0134,  0.1652]],
       grad_fn=<AddmmBackward0>)


#Discovering activation functions
WHY WE NEED ACTIVATION FUCNTION?
----Actiivation function add non-linearity to the nertwork
---A model can learn more complex relationships with non-linearity

In [ ]:
#sigmoid activation function

import torch
#print(torch.__version__)
import torch.nn as nn
input=torch.tensor([[6.0]])

sigmoid=nn.Sigmoid()
output=sigmoid(input)
print(output)

tensor([[0.9975]])


In [ ]:
#Activation function as last layer
model=nn.Sequential(
    nn.Linear(6,4), # 1st linear layer
    nn.Linear(4,1), #2nd linaer layer
    nn.Sigmoid() # Activation function
)

Getting aquainted with softmax



*   Used in multi-class classification.

*   Takes N-element vector as input and outputs vector of same size.


*   Outputs a probability distribution.








In [ ]:
import torch
import torch.nn as nn
# create an input tensor
input=torch.tensor(
    [[4.3,6.1,2.3]]
)
# Apply softmax along the last dimension
probabilities=nn.Softmax(dim=-1) # Dim=-1 inndicates softmax is applied to the input's last deimension.
output=probabilities(input)
print(output)

tensor([[0.1392, 0.8420, 0.0188]])


#Unit two:Running a forward pass

Binary Classificatin: Forward Pass

In [ ]:
#ctreat input data of shape 5*6
import torch
import torch.nn as nn
input_tensor = torch.tensor([[1, 2, 3, 4, 5, 6],
                             [7, 8, 9, 10, 11, 12],
                             [13, 14, 15, 16, 17, 18],
                             [19, 20, 21, 22, 23, 24],
                             [25, 26, 27, 28, 29, 30]],dtype=torch.float)

In [ ]:
#creat binary classification model
model=nn.Sequential(
                    nn.Linear(6,4),
                    nn.Linear(4,1),
                    nn.Sigmoid()
)
#pass input data trhough model
output=model(input_tensor)
print(output)

tensor([[0.7452],
        [0.9499],
        [0.9919],
        [0.9987],
        [0.9998]], grad_fn=<SigmoidBackward0>)


Multi-class classification: forward pass


In [ ]:
# specify the number of classes
n_classes=3
#create multiclass classification model
model= nn.Sequential(
    nn.Linear(6,4),
    nn.Linear(4,n_classes),
    nn.Softmax(dim=-1)

)
output=model(input_tensor)
print((output))

tensor([[4.1097e-01, 5.7729e-01, 1.1747e-02],
        [3.2633e-01, 6.7356e-01, 1.0458e-04],
        [2.4796e-01, 7.5204e-01, 8.9089e-07],
        [1.8327e-01, 8.1673e-01, 7.3824e-09],
        [1.3248e-01, 8.6752e-01, 5.9831e-11]], grad_fn=<SoftmaxBackward0>)


Regression: forward pass


In [ ]:
#create regression model
model= nn.Sequential(
    nn.Linear(6,4),
    nn.Linear(4,1)
)
output=model(input_tensor)
print(output)

tensor([[0.6557],
        [1.0573],
        [1.4590],
        [1.8607],
        [2.2623]], grad_fn=<AddmmBackward0>)


Using loss functions to assess model predictions

---


*   Gives feedback to model during training
*   Takes in model prediction y_hat and groud truth y
* Outputs a float




One-hot encoding concept
* loss =f(y_hat,y)
* y is a single value either 0 or 1
* y_hat is a tensor( output of a softmax)
* to compare tensor with an integer we convert y to one hot concoding
* if num of class N=3 then for y=0 we would assign y= 1,0,0 meaning first class ( 0 class) is given value.

Transforming labels with one-hot encoding

In [ ]:
import torch.nn.functional as F
F.one_hot(torch.tensor(0),num_classes=3
          )
F.one_hot(torch.tensor(1),num_classes=3
          )
F.one_hot(torch.tensor(2),num_classes=3
          )

tensor([0, 0, 1])

Cross entropy loss in PyTorch


In [ ]:
from torch.nn import CrossEntropyLoss
scores=torch.tensor([[-0.1211,0.1059]])
one_hot_target= torch.tensor([[1,0]])
criterion=CrossEntropyLoss()
criterion(scores.double(),one_hot_target.double())

tensor(0.8131, dtype=torch.float64)

Uisng derivatives to update model parameters

Backpropagation in PyTorch

In [ ]:
import torch
import torch.nn as nn

# Define the sample input tensor
sample = torch.randn(1, 16)  # A batch of 1 with 16 features

# Create the model
model = nn.Sequential(
    nn.Linear(16, 8),
    nn.Linear(8, 4),
    nn.Linear(4, 2)
)

# Run a forward pass
prediction = model(sample)

# Define the target as a class index (not one-hot encoded)
target = torch.tensor([1])  # Class index (e.g., for a batch size of 1)

# Calculate the loss and compute the gradients
criterion = nn.CrossEntropyLoss()
loss = criterion(prediction, target)

# Backward pass to compute gradients
loss.backward()

# Print the loss for verification
print("Loss:", loss.item())


Loss: 0.5056609511375427


In [ ]:
# Access each layer's grdaients
print(model[0].bias.grad)
print(model[0].weight.grad)

tensor([ 0.0061, -0.0415, -0.0978,  0.0040, -0.0804, -0.0434, -0.0024,  0.0642])
tensor([[-0.0004, -0.0083,  0.0067,  0.0084, -0.0056,  0.0048,  0.0017, -0.0017,
          0.0022, -0.0022,  0.0049, -0.0028,  0.0021, -0.0013,  0.0097,  0.0046],
        [ 0.0030,  0.0566, -0.0453, -0.0571,  0.0379, -0.0329, -0.0115,  0.0117,
         -0.0151,  0.0152, -0.0332,  0.0193, -0.0140,  0.0092, -0.0658, -0.0313],
        [ 0.0072,  0.1332, -0.1067, -0.1343,  0.0892, -0.0773, -0.0271,  0.0274,
         -0.0356,  0.0358, -0.0782,  0.0455, -0.0330,  0.0216, -0.1550, -0.0736],
        [-0.0003, -0.0054,  0.0044,  0.0055, -0.0036,  0.0032,  0.0011, -0.0011,
          0.0015, -0.0015,  0.0032, -0.0019,  0.0013, -0.0009,  0.0063,  0.0030],
        [ 0.0059,  0.1095, -0.0877, -0.1104,  0.0733, -0.0636, -0.0223,  0.0226,
         -0.0292,  0.0294, -0.0643,  0.0374, -0.0271,  0.0177, -0.1274, -0.0605],
        [ 0.0032,  0.0591, -0.0473, -0.0596,  0.0396, -0.0343, -0.0120,  0.0122,
         -0.0158,  0.01

updating the model parameters

In [ ]:
lr=0.001
#update the weights
weight=model[0].weight
weight_grad=model[0].weight.grad
weight=weight-lr*weight_grad
#update the biases
bias=model[0].bias
bias_grad=model[0].bias
bias=bias-lr*bias_grad

Gradient descent


*   For non-convex funstions, we will use an ietrative approach such as gtradient descent
*   In pyTorch, as optimizer takes care of weight updates
* The most common optimizer us stochastic gradient descent (SGD)






In [ ]:
import torch.optim as optim
#create the optimizer
optimizer =optim.SGD(model.parameters(),lr=0.001)
optimizer.zero_grad()
optimizer.step()

Writing our first training loop
---
 Training a neural network



1.   Create a model
2.   Choose a loss function
3. Create a dataset
4. Define an optimizer
5. Run a training loop, where each sample of the dataset, we repeat:


*   Calculating loss(forward pass)
*   Calculating the local gradients
* Updating model parameters








Introducing the Data Science Salary dataset


*   the target is salary is US dollars;it is not a category but a continuous quantity
*   For regreassion problems, we can not use softmax or sigmois as last actication function
* We need different loss function than cross-entropy



In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("saurabhshahane/data-science-jobs-salaries")

print("Path to dataset files:", path)

Path to dataset files: /root/.cache/kagglehub/datasets/saurabhshahane/data-science-jobs-salaries/versions/2


In [ ]:
import pandas as pd

# Load the dataset into a pandas DataFrame
dataset_path = path + '/Data Science Jobs Salaries.csv'  # Modify this if the dataset has a different file name
df = pd.read_csv(dataset_path)

# Show the first few rows of the dataset
df.head()


work_year experience_level employment_type                  job_title  \
0     2021e               EN              FT    Data Science Consultant   
1      2020               SE              FT             Data Scientist   
2     2021e               EX              FT       Head of Data Science   
3     2021e               EX              FT               Head of Data   
4     2021e               EN              FT  Machine Learning Engineer   

   salary salary_currency  salary_in_usd employee_residence  remote_ratio  \
0   54000             EUR          64369                 DE            50   
1   60000             EUR          68428                 GR           100   
2   85000             USD          85000                 RU             0   
3  230000             USD         230000                 RU            50   
4  125000             USD         125000                 US           100   

  company_location company_size  
0               DE            L  
1               US            L  
2               RU            M  
3               RU            L  
4               US            S

In [ ]:
# Keep only the specified columns
columns_to_keep = ['experience_level', 'employment_type', 'remote_ratio', 'company_size', 'salary_in_usd']
df_filtered = df[columns_to_keep]
df_filtered.head()

experience_level employment_type  remote_ratio company_size  salary_in_usd
0               EN              FT            50            L          64369
1               SE              FT           100            L          68428
2               EX              FT             0            M          85000
3               EX              FT            50            L         230000
4               EN              FT           100            S         125000

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
# Apply LabelEncoder to each categorical column
df_filtered['experience_level'] = label_encoder.fit_transform(df_filtered['experience_level'])
df_filtered['employment_type'] = label_encoder.fit_transform(df_filtered['employment_type'])
df_filtered['remote_ratio'] = label_encoder.fit_transform(df_filtered['remote_ratio'])
df_filtered['company_size'] = label_encoder.fit_transform(df_filtered['company_size'])

<ipython-input-52-b39208251fb1>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['experience_level'] = label_encoder.fit_transform(df_filtered['experience_level'])
<ipython-input-52-b39208251fb1>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['employment_type'] = label_encoder.fit_transform(df_filtered['employment_type'])
<ipython-input-52-b39208251fb1>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_inde

In [ ]:
df_filtered.head()

experience_level  employment_type  remote_ratio  company_size  \
0                 0                2             1             0   
1                 3                2             2             0   
2                 1                2             0             1   
3                 1                2             1             0   
4                 0                2             2             2   

   salary_in_usd  
0          64369  
1          68428  
2          85000  
3         230000  
4         125000

Introducing the Mean Squared Error Loss






In [ ]:
def mean_squared_loss(prediction,target):
  return np.mean((prediction-target)**2)

# in PyTorch
criterion=nn.MSELoss()
loss=criterion(prediction,target)

/usr/local/lib/python3.10/dist-packages/torch/nn/modules/loss.py:608: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([1, 2])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


Before the training loop


In [ ]:
import torch
from torch.utils.data import TensorDataset, DataLoader
features= df_filtered[['experience_level', 'employment_type', 'remote_ratio', 'company_size']]
target=df_filtered[['salary_in_usd']]
# Convert the features and target to NumPy arrays and then to PyTorch tensors
features_tensor = torch.tensor(features.values, dtype=torch.float32)  # Convert to NumPy array first
target_tensor = torch.tensor(target.values, dtype=torch.float32)
# Create the dataset and the dataloader
dataset = TensorDataset(features_tensor, target_tensor)
dataloader=DataLoader(dataset,batch_size=4,shuffle=True)

#create the model
model=nn.Sequential(nn.Linear(4,2),
                    nn.Linear(2,1))
# create the loss and the optimizer
criterion= nn.MSELoss()
optimzer=optim.SGD(model.parameters(),lr=0.001)

The training loop

In [ ]:
num_epochs=5
#Loop throught the dataset multiple times
for epoch in range(num_epochs):
  for data in dataloader:
    #set the gradients to zero
    optimizer.zero_grad()
    #get the feature and target from the data loader
    features_tensor,target_tensor= data
    # Run a forward pass
    pred= model(features_tensor)
    #compute loss and gradients
    loss=criterion(pred,target_tensor)
    loss.backward()
    #update the paramers
    optimizer.step()

# Unit Three: Discovering activation functions between layers
Sigmoid functions:


*   Bounded between 0 and 1
*   Can be used anywhere in the network
 Gradients:


*   Approach to zero for low and high value of x
*   Cause function to saturate

Sigmoid function saturation can lead to vanishing gradients during backporpagation
Same for softmax






In [ ]:
relu=nn.ReLU()
leaky_relu=nn.LeakyReLU(negative_slope=0.05)


A deeper dive into NN architectutre

Coutning the number of parameters


In [ ]:
model=nn.Sequential(
    nn.Linear(8,4),
    nn.Linear (4,2)
)



manually calculating the number of parameters:


*   first layers has 4 neurons, each neuron has (N+1),where N is dimension of previous layers outputs. So each neuron  8+1=9, total 4*9=36 parameters
*   second layer 2*(4+1)=10 parameters
* Total= 46 learnable parameters



using PyTorch:


*   .numel(): returns the number of elements in the tensor




In [ ]:
total=0
for parameters in model.parameters():
  total+=parameters.numel()
print(total)

46


Layer initialization and transfer learning

In [ ]:
import torch.nn as nn
layer=nn.Linear(64,128)
print(layer.weight.min(),layer.weight.max())

tensor(-0.1249, grad_fn=<MinBackward1>) tensor(0.1249, grad_fn=<MaxBackward1>)


* layer weights are initialized to small values
* layer outputs can explode if inputs and weights are not normalized
* weights can be initialized using different methods(e.g., with a uniform distribution)


In [ ]:
import torch.nn as nn
layer=nn.Linear(64,128)
nn.init.uniform_(layer.weight)
print(custom_layer.fc)

NameError: name 'custom_layer' is not defined

Tranfer learning nad fine-tuning


In [ ]:
import torch
layer=nn.Linear(64,128)
torch.save(layer,'layer.pth')
new_layer=torch.load('layer.pth')

<ipython-input-2-695a1186e317>:4: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  new_layer=torch.load('layer.pth')


Fine tuning


*   Fine-tuning= A type of transfer learning
*   Smaller learning rate
*   Not every layer is trained (we freeze some of them)
*   Rule of thumb: freeze early layers of network and fine-tune layers closer to output layer



In [ ]:
import torch.nn as nn
model=nn.Sequential(nn.Linear(64,128),
                    nn.Linear(128,256))
for name,param in model.named_parameters():
  if name== '0.weight':
    param.requires_grad=False

#Unit Four

A deeper dive into loading data

In [ ]:
import pandas as pd
animals=pd.read_csv('zoo.csv')

Defining features

In [ ]:
import numpy as np

features = animals.iloc[:, 1:-1]
X = np.array(features).astype(float)  # Convert to float type

print(X)

[[1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 1. 0. 1.]
 [0. 0. 1. ... 1. 0. 0.]
 ...
 [1. 0. 0. ... 1. 0. 1.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 1. 0. 0.]]


defining targets

In [ ]:
target = animals.iloc[:, -1]
y = np.array(target)
print(y)

[1 1 4 1 1 1 1 4 4 1 1 2 4 7 7 7 2 1 4 1 2 2 1 2 6 5 5 1 1 1 6 1 1 2 4 1 1
 2 4 6 6 2 6 2 1 1 7 1 1 1 1 6 5 7 1 1 2 2 2 2 4 4 3 1 1 1 1 1 1 1 1 2 7 4
 1 1 3 7 2 2 3 7 4 2 1 7 4 2 6 5 3 3 4 1 1 2 1 6 1 7 2]


Recalling TensorDataset

In [ ]:
import torch
from torch.utils.data import TensorDataset
#instantiate dataset class
dataset=TensorDataset(torch.tensor(X).float(),torch.tensor(y).float())
#Access an individual sample
sample=dataset[0]
feature,label=sample
print("feature",feature)
print("label",label)

feature tensor([1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 4., 0., 0., 1.])
label tensor(1.)


Recalling DataLoader

In [ ]:
from torch.utils.data import DataLoader
batch_size=2
shuffle=True
#Create a DataLoader
dataloader= DataLoader(dataset,batch_size=batch_size,shuffle=shuffle)
#Iterate over the DataLoader
for batch_inputs, batch_labels in dataloader:
  print('batch inputs:', batch_inputs)
  print('batch lables:', batch_labels)

batch inputs: tensor([[0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1.],
        [1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 2., 1., 0., 0.]])
batch lables: tensor([4., 1.])
batch inputs: tensor([[0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 4., 0., 0., 0.],
        [1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 4., 1., 1., 1.]])
batch lables: tensor([5., 1.])
batch inputs: tensor([[1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 4., 1., 0., 0.],
        [1., 0., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 2., 1., 0., 0.]])
batch lables: tensor([1., 1.])
batch inputs: tensor([[1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 4., 1., 0., 0.],
        [0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 2., 1., 1., 0.]])
batch lables: tensor([1., 2.])
batch inputs: tensor([[0., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 2., 1., 0., 0.],
        [0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 4., 0., 0., 0.]])
batch lables: tensor([2., 5.])
batch inputs: tensor([[0., 1.,

Evaluating model performance

Calculating training loss
* For each epoch:
  * we sum up the loss for each iteration of the training set dataloader
  * at the end of the epoch, we calculate the mean training loss

In [ ]:
traning_loss=0.0
for i,data in enumerate(trainloader,0):
  #Run the forward pass
  ...
  #Calculate the loss
  loss= criterion(outputs,lables)
  #Calclulate the gradients
  ...
  #Calculate and sum the loss
  training_loss+=loss/item()
epoch_loss= training_loss/len(trainloader)


NameError: name 'trainloader' is not defined

Calclulating the validation loss
  * After the training epoch, we iterate over the validation set and calculate the average validation loss

In [ ]:
valiadtion_loss=0
model.eval() #put the model in evaluation mode
with torch.no_grad(): #speed up the forward pass
  for i,data in enumerate(validationloader,0);
  #Run the forward pass
  ...
  #Calculate the loss
  loss= criterion(outputs,lables)
  valiadtion_loss+=loss/item()
epoch_loss= valiadtion_loss/len(validationloader)
model.train()


Calculating accuracy with torchmetrics

In [ ]:
import torchmetrics
#create accuracy metric using torch metrics
metric= torchmetrics.accuracy(task="multiclass",num_classes=3)
for i,data in enumerate (dataloader,0):
  features,labels=data
  output=model(features)
  acc=metric(output,labels.argmax(dim=-1))
#Calculate accuracy over the whole epoch
acc=metric.compute()
print(f"Accuracy on all data:{acc}")
#Reset the metric for the next epoch(training or validation)
metric.reset()

Fighting overfittting
Strategies:
  * Reducing model size or adding dropout layer
  * Using weight decay to force parameters to remain small
  * Obtain new data or augmenting data

Regularization using a dropout layer

In [5]:
import torch
model= nn.Sequential(
    nn.Linear(8,4),
    nn.ReLU(),
    nn.Dropout(p=0.5)

    )
features= torch.randn((1,8))
output=model(features)

print(output)

tensor([[1.8871, 0.0000, 0.0000, 0.0000]], grad_fn=<MulBackward0>)


* Randomly zeroes out elements of the input tensor during training.
* Dropout is added after the activation function.
* Behaves differently during training and evaluation; we must remember to switch modes using model.train() and model.eval()

Regularization with weight decay

Optimizer=optim.SGD(model.parameters(),lr=1e-3,weight_decay=1e-4)

* Optimizer's weight_decay takes values between zero and one ( Typically small value, e.g. 1e-3
* Weight decay adds penalty to loss function to discourage large weights and biases.
* The higher the parameter, the less likely the model is to overfit.

Improving model performance

Steps to maximize performance

* Overfit the training set
  * Can we solve the problem?
  * sets a performance baseline
* Reduce overfitting
  * Imrpove performances on the validation set
* Fine-tune hyperparameters

Step 1: overfit the training set

* Modify the training loop to overfit a single data point (batch size of 1)
  * should reach 1.0 accuracy and 0 loss
  * helps findings bugs in the code

* Goal: minimize the training loss
  * create large enough model
  * use a default learning rate
  

In [ ]:
features,labels= next(iter(trainloader))
for i in range(1e-3):
  outputs= model(features)
  loss= criterion(outputs,lables)
  loss.backward()
  optimizer.step()


Step 2: reduce overfitting
* Goal: maximize the validation accuracy
* Experiment with:
  * Dropoout
  * Data augmentation
  * Weight decay
  * Reducing model capacity
* Keep track of each hyperparameter and report maximum validation accuracy


Step 3: fine-tune hyperparameters


In [6]:
# grid search
for factor in range(2,6):
  lr=10**-factor
# Random search
factor=np.random.uniform(2,6)
lr=10**-factor

NameError: name 'np' is not defined

A good book : https://www.deeplearningbook.org/